require('dotenv').config();
const express=require('express');
const cors=require('cors');
const connectDB=require('./config/db');
const path = require("path");
connectDB();const app=express();
app.use(cors());
app.use(express.json());
app.use("/uploads", express.static(path.join(__dirname, "uploads")));
app.use('/api/auth',require('./routes/authRoutes'));
app.use('/api/profile',require('./routes/profileRoutes'));
app.listen(process.env.PORT,()=>console.log('Server running'));