const ACTIVITY_TYPE = {
  USER_REGISTERED: 'USER_REGISTERED',
  OPPORTUNITY_POSTED: 'OPPORTUNITY_POSTED',
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED'
};

const ACTIVITY_TYPE_ARRAY = Object.values(ACTIVITY_TYPE);

module.exports = { ACTIVITY_TYPE, ACTIVITY_TYPE_ARRAY };
