const NOTIFICATION_TYPE = {
  MESSAGE: 'MESSAGE',
  OPPORTUNITY: 'OPPORTUNITY',
  PICKUP: 'PICKUP',
  APPLICATION: 'APPLICATION'
};

const NOTIFICATION_TYPE_ARRAY = Object.values(NOTIFICATION_TYPE);

module.exports = { NOTIFICATION_TYPE, NOTIFICATION_TYPE_ARRAY };
