const PICKUP_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const PICKUP_STATUS_ARRAY = Object.values(PICKUP_STATUS);

module.exports = { PICKUP_STATUS, PICKUP_STATUS_ARRAY };
