const OTP_LENGTH = 6;
const OTP_EXPIRY_MINUTES = 10;
const MAX_OTP_ATTEMPTS = 5;
const MAX_OTP_RESEND = 5;
const OTP_COOLDOWN_SECONDS = 60;
const OTP_LOCK_HOURS = 24;

const SALT_ROUNDS = parseInt(process.env.BCRYPT_SALT_ROUNDS, 10) || 10;

module.exports = {
  OTP_LENGTH,
  OTP_EXPIRY_MINUTES,
  MAX_OTP_ATTEMPTS,
  MAX_OTP_RESEND,
  OTP_COOLDOWN_SECONDS,
  OTP_LOCK_HOURS,
  SALT_ROUNDS
};
