const OTP_LENGTH = 6;
const OTP_EXPIRY_MINUTES = 10;
const MAX_OTP_ATTEMPTS = 5;
const MAX_OTP_RESEND = 5;
const OTP_COOLDOWN_SECONDS = 60;
const OTP_LOCK_HOURS = 24;

const SALT_ROUNDS = parseInt(process.env.BCRYPT_SALT_ROUNDS, 10) || 10;

const PASSWORD_MIN_LENGTH = 8;
const PASSWORD_MAX_LENGTH = 128;
const PASSWORD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?`~]).{8,128}$/;

const ACCESS_TOKEN_EXPIRY_MINUTES = 15;
const REFRESH_TOKEN_EXPIRY_DAYS = 7;
const REFRESH_TOKEN_REMEMBER_EXPIRY_DAYS = 30;
const REFRESH_TOKEN_BYTES = 48;

const LOGIN_MAX_ATTEMPTS = 5;
const LOGIN_LOCK_MINUTES = 30;

module.exports = {
  OTP_LENGTH,
  OTP_EXPIRY_MINUTES,
  MAX_OTP_ATTEMPTS,
  MAX_OTP_RESEND,
  OTP_COOLDOWN_SECONDS,
  OTP_LOCK_HOURS,
  SALT_ROUNDS,
  ACCESS_TOKEN_EXPIRY_MINUTES,
  REFRESH_TOKEN_EXPIRY_DAYS,
  REFRESH_TOKEN_REMEMBER_EXPIRY_DAYS,
  REFRESH_TOKEN_BYTES,
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  PASSWORD_REGEX,
  LOGIN_MAX_ATTEMPTS,
  LOGIN_LOCK_MINUTES
};
