const ADMIN_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  RESTORE: 'RESTORE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  ASSIGN: 'ASSIGN',
  EXPORT: 'EXPORT',
  IMPORT: 'IMPORT'
};

const ADMIN_ACTIONS_ARRAY = Object.values(ADMIN_ACTIONS);

module.exports = { ADMIN_ACTIONS, ADMIN_ACTIONS_ARRAY };
