const APPLICATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN'
};

const APPLICATION_STATUS_ARRAY = Object.values(APPLICATION_STATUS);

module.exports = { APPLICATION_STATUS, APPLICATION_STATUS_ARRAY };
