const NOTIFICATION_TYPE = {
  NEW_MESSAGE: 'NEW_MESSAGE',
  OPPORTUNITY_ACCEPTED: 'OPPORTUNITY_ACCEPTED',
  OPPORTUNITY_REJECTED: 'OPPORTUNITY_REJECTED',
  APPLICATION_RECEIVED: 'APPLICATION_RECEIVED',
  SYSTEM: 'SYSTEM'
};

const NOTIFICATION_TYPE_ARRAY = Object.values(NOTIFICATION_TYPE);

module.exports = { NOTIFICATION_TYPE, NOTIFICATION_TYPE_ARRAY };
