const OPPORTUNITY_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED'
};

const OPPORTUNITY_STATUS_ARRAY = Object.values(OPPORTUNITY_STATUS);

module.exports = { OPPORTUNITY_STATUS, OPPORTUNITY_STATUS_ARRAY };
