const TARGET_TYPES = {
  USER: 'USER',
  OPPORTUNITY: 'OPPORTUNITY',
  APPLICATION: 'APPLICATION',
  MESSAGE: 'MESSAGE',
  ADMINLOG: 'ADMINLOG'
};

const TARGET_TYPES_ARRAY = Object.values(TARGET_TYPES);

module.exports = { TARGET_TYPES, TARGET_TYPES_ARRAY };
